name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pytest black  # Install both pytest and black here
    - name: Install Pylint
      run: pip install pylint        
    - name: Lint with pylint
      run: |
        make lint
    - name: Install pytest
      run: pip install pytest        
    - name: Test with pytest
      run: |
        make test
    - name: Install Black
      run: pip install black  # Alternative: Install black here if you prefer
    - name: Format code
      run: |
        make format
